# Generated by Django 3.0.2 on 2020-01-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timstamp',
            new_name='timestamp',
        ),
    ]
